development:
  cloud_name: 'hwtphffjr'
  api_key: '487578641544343'
  api_secret: 'X2IyHSXByi8P9IxJtjTqhRDneEA'
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: 'hwtphffjr'
  api_key: '487578641544343'
  api_secret: 'X2IyHSXByi8P9IxJtjTqhRDneEA'
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: 'hwtphffjr'
  api_key: '487578641544343'
  api_secret: 'X2IyHSXByi8P9IxJtjTqhRDneEA'
  enhance_image_tag: true
  static_image_support: false
