# development:
#   cloud_name: 'hwtphffjr'
#   api_key: '487578641544343'
#   api_secret: 'X2IyHSXByi8P9IxJtjTqhRDneEA'
#   enhance_image_tag: true
#   static_image_support: false
# test:
#   cloud_name: 'hwtphffjr'
#   api_key: '487578641544343'
#   api_secret: 'X2IyHSXByi8P9IxJtjTqhRDneEA'
#   enhance_image_tag: true
#   static_image_support: false
# production:
#   cloud_name: 'hwtphffjr'
#   api_key: ENV['CLOUDINARY_API_KEY']
#   api_secret: ENV['CLOUDINARY_API_SECRET']
#   enhance_image_tag: true
#   static_image_support: true  
